---
- name: "Configuracion de servidor"
  hosts: localhost
  connection: local
  become: yes  
  tasks:
    - name: "Instalar Apache"
      apt:
        name: apache2
        state: present
        update_cache: yes